export const REQUEST_EVENTS_PENDING = 'REQUEST_MOVIES_PENDING';
export const REQUEST_EVENTS_SUCCESS = 'REQUEST_MOVIES_SUCCESS';
export const REQUEST_EVENTS_FAILED = 'REQUEST_MOVIES_FAILED';

export const REQUEST_EVENT_DETAIL_PENDING = 'REQUEST_EVENT_DETAIL_PENDING';
export const REQUEST_EVENT_DETAIL_SUCCESS = 'REQUEST_EVENT_DETAIL_SUCCESS';
export const REQUEST_EVENT_DETAIL_FAILED = 'REQUEST_EVENT_DETAIL_FAILED';

export const WITHIN_DISTANCE = 100;
export const N_EVENTS = 5;
