export const WITHIN_DISTANCE = 100;
export const N_EVENTS = 5;

export const REQUEST_EVENTS_PENDING = 'REQUEST_EVENTS_PENDING';
export const REQUEST_EVENTS_SUCCESS = 'REQUEST_EVENTS_SUCCESS';
export const REQUEST_EVENTS_FAILED = 'REQUEST_EVENTS_FAILED';

export const REQUEST_EVENT_DETAIL_PENDING = 'REQUEST_EVENT_DETAIL_PENDING';
export const REQUEST_EVENT_DETAIL_SUCCESS = 'REQUEST_EVENT_DETAIL_SUCCESS';
export const REQUEST_EVENT_DETAIL_FAILED = 'REQUEST_EVENT_DETAIL_FAILED';

export const REQUEST_USER_LOCATION_PENDING = 'REQUEST_USER_LOCATION_PENDING';
export const REQUEST_USER_LOCATION_SUCCESS = 'REQUEST_USER_LOCATION_SUCCESS';
export const REQUEST_USER_LOCATION_FAILED = 'REQUEST_USER_LOCATION_FAILED';

export const MOUSE_OVER_MARKER = 'MOUSE_OVER_MARKER';
export const MOUSE_OUT_MARKER = 'MOUSE_OUT_MARKER';
